### ISSUE TITLE
UI Design on CyBear Jinni Website

### ISSUE THREAD

**Issue by LunlunChin** [CyBear-Jinni/CBJ_Site#100]
will create some UI design on Figma for the website

**Comment by guyluz11** [comment]
Just adding parts of my vision for the app.

I would love for the app to be a little animated
So for example the logos of the companies on the home page will scroll between all our supported integrations.
For that we can use this package that I have found [scroll_loop_auto_scroll](https://pub.dev/packages/scroll_loop_auto_scroll)
Using the Horizontal with dynamic item size
![dynamic_size](https://user-images.githubusercontent.com/9304740/194723499-c47f3634-77a9-4c33-9819-30c822293796.gif)

And scroll behavior can change to be one section of the screen each time
Without any in-between sections scrolls 
Maybe with the package [scrolling_page_indicator](https://pub.dev/packages/scrolling_page_indicator) but vertical and not horizontal.

**Comment by guyluz11** [comment]
And creating small animations in [rive](https://rive.app/)

**Comment by guyluz11** [comment]
As written in the readme [this is](https://www.figma.com/file/MhxmWzNxRX2KR17uwsYehf/CyBear-Jinni-Site-moc-1.0.0) the new moc of the site.

Let's create it in a new branch.

**Comment by guyluz11** [comment]
Pr of new moc got merged, site will update in a complete of hours to include the new version

Thanks @LunlunChin for the amazing work
