### ISSUE TITLE
Update packages to the last version

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/cbj_site#117]
Please update packages to the last version

**Comment by chiragtyagi2003** [comment]
hey, would like to contribute!

**Comment by guyluz11** [comment]
Great just great to pull request

**Comment by Opshanka** [comment]
Could I contribute now

**Comment by guyluz11** [comment]
> Could I contribute now

Sure

**Comment by gantanikhilraj** [comment]
Hey @guyluz11 , Can I work on this, please assign it to me.

**Comment by guyluz11** [comment]
> Hey @guyluz11 , Can I work on this, please assign it to me.

Sure, please open a pr to dev

**Comment by guyluz11** [comment]
Done, closing
