### ISSUE TITLE
Image not loading in main page

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#157]
The image keeps loading and not showing: 

![image](https://github.com/CyBear-Jinni/CBJ_Site/assets/34707669/033dbb26-4d9e-47cb-8b45-c73f7e917b36)

Using chrome

**Comment by guyluz11** [comment]
The site uses a cache so you might have an old version of the site.

Try to open it in incognito or rest cache of the site by clicking `ctrl +f5`

If it changed pleas revisit all of the issues your have opened

**Comment by Tamir198** [comment]
Seems like a one time problem, will close the issue
