### ISSUE TITLE
Contact me is not working

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#47]
When clicking the add button (after clicking contact me) nothing is happening (from user point of view - I got no feedback and the dialog stay the same)

![image](https://user-images.githubusercontent.com/34707669/121959396-64ba6a80-cd6d-11eb-93ce-2da1a9a184ca.png)

**Comment by guyluz11** [comment]
As issue #37 says, we are going to delete all the contact us section from the site.
So this popup will disappear with it.

**Comment by guyluz11** [comment]
Removed Contact Us button in the last pull request.
