### ISSUE TITLE
I can write letters in contact me/phone number

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#48]
When I click contact me button, I can put letters for the input of the phone number:

![image](https://user-images.githubusercontent.com/34707669/121959752-dbeffe80-cd6d-11eb-876b-791f1e650da6.png)

**Comment by guyluz11** [comment]
As issue #37 says, we are going to delete all the contact us section from the site.
So this popup will disappear with it.

**Comment by guyluz11** [comment]
Removed Contact Us button in the last pull request.
