### ISSUE TITLE
App store button is not doing anything

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#49]
Do you have your app available in the app store? because the app store button is not doing anything when its clicked

![image](https://user-images.githubusercontent.com/34707669/121960081-4c971b00-cd6e-11eb-8c62-6bf0e82ff4cb.png)

**Comment by guyluz11** [comment]
For now our app does not exist in the App Store so we put place holder there.
Thanks to his issue we will now remember to fix this whenever we get in in the App Store.

Thanks.

**Comment by guyluz11** [comment]
The commit got released to production.

Closing the issue, thanks.
