### ISSUE TITLE
Image weird white line

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#58]
On your site you have this image:

![image](https://user-images.githubusercontent.com/34707669/133907834-ef97d4eb-07bf-4937-bfbc-35272704de22.png)

As you can see there is a white line to the left of the image, is this a bug or this is the design of the site?

**Comment by karanpatel2329** [comment]
i would to like to work on this issue. Please assigned it to me. @guyluz11

**Comment by guyluz11** [comment]
This is now yours @karanpatel2329

**Comment by guyluz11** [comment]
A new version of the home page just got deployed (will be updated soon) and this section got changed.

Will close this issue now as it is no longer relevant to the new version.

Thanks
