### ISSUE TITLE
Border is not showing on mobile view

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#60]
When you check this part of the website on large screens everything is ok:

![image](https://user-images.githubusercontent.com/34707669/135172264-79d87fab-80c5-4767-b31f-0ea8c485f4f8.png)

But on mobile screen it looks like the bottom border is not there:

![image](https://user-images.githubusercontent.com/34707669/135172392-17d9ed7d-1422-4e5b-bdd2-336aeea3fc99.png)

![image](https://user-images.githubusercontent.com/34707669/135172425-54d69de7-c73f-46b5-b289-ae4a7eb95269.png)

**Comment by karanpatel2329** [comment]
Hello @Tamir198 ,

I can solve this issue and i want to work on it. Please assigned to me.

Thank You

**Comment by guyluz11** [comment]
Sure @karanpatel2329 this one is now yours.

**Comment by Tamir198** [comment]
Hey, @karanpatel2329.

I have only opened this issue.
If @guyluz11  assign it to you its yours

**Comment by karanpatel2329** [comment]
I have this bug. Please merge my PR.
![asasas](https://user-images.githubusercontent.com/51056125/135745305-8a4b8d1b-4927-47e1-b779-674deb52d8d1.jpg)

**Comment by Aaliya-Ali** [comment]
Hey @guyluz11,
I see that the issue is still open, it seems like an easy fix. Please assign it to me. Also, I'd like to know if this issue is hacktoberfest accepted.

**Comment by guyluz11** [comment]
@Aaliya-Ali you can open pr for that no need for an assignment.

It is Hacktoberfest accepted and I will add the `hacktoberfest-accept` label on pr if it got merged.

**Comment by Aaliya-Ali** [comment]
Sure thanks for the info!

**Comment by guyluz11** [comment]
Done, 

Closing this issue, fix will be in the next production version.

Thanks
