### ISSUE TITLE
Frequently asked questions title is not the same length in mobile

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Site#65]
Frequently asked questions title is not the same length in mobile like the other pages.

Please change it to be the same as the other page titles on mobile 

![image](https://user-images.githubusercontent.com/9304740/136687993-abf3f269-184c-417e-86ad-a942907376c0.png)

![image](https://user-images.githubusercontent.com/9304740/136688005-dbb93ef3-fb6a-4ff7-a4f3-25adac953457.png)

**Comment by agent515** [comment]
@guyluz11 I can take this one.

**Comment by guyluz11** [comment]
You got it @agent515

**Comment by guyluz11** [comment]
Just to be clear the issue is about the space from the top.
Not the size of the text.

**Comment by guyluz11** [comment]
I am not sure what is that, I have just successfully cloned your fork and it is working.
Do you want to jump to a discord call and show me?


[<img src="https://cdn.icon-icons.com/icons2/2108/PNG/512/discord_icon_130958.png" height="80">](https://discord.gg/mUXfwUY)

**Comment by agent515** [comment]
Thanks, @guyluz11 

> I am not sure what is that, I have just successfully cloned your fork and it is working.
Do you want to jump to a discord call and show me?

I'll try to figure out what's the problem a bit later by myself. I'll let you know if any help is required.
