### ISSUE TITLE
Text overlapping

### ISSUE THREAD

**Issue by Tamir198** [CyBear-Jinni/CBJ_Site#88]
Hey, I have noticed this UI bug:

![image](https://user-images.githubusercontent.com/34707669/168070735-a3397ecc-9f47-4e0e-84fd-27c4597cacbe.png)

**Comment by Tamir198** [comment]
Its a 24 inch screen

**Comment by piyushkumar12111111** [comment]
Hey, Please assign this issue to me

**Comment by guyluz11** [comment]
Sure

**Comment by guyluz11** [comment]
Hi @Tamir198 

We have a new home page, it is using the same widget as the one that you mentioned.

Can you try to reproduce the issue again just in our new version?

![image](https://user-images.githubusercontent.com/9304740/198908639-03b7e626-924c-4606-a8dd-430abc63a10c.png)


Thanks

**Comment by Tamir198** [comment]
Seems ok now

**Comment by guyluz11** [comment]
Great, will close the issue
