### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by guyluz11** [CyBear-Jinni/CBJ_Site#97]
Please update all project dependencies to the last version except `youtube_player_iframe` as it seems that the new version does not load our video.

If you find a way to make `youtube_player_iframe` it will be a bonus :)

**Comment by superiorsd10** [comment]
@guyluz11 Can I work on this issue?

**Comment by guyluz11** [comment]
Yes

**Comment by guyluz11** [comment]
Thanks for the pr
And happy Hacktoberfest

**Comment by superiorsd10** [comment]
@guyluz11 You're most welcome :) and yes, happy hacktoberfest!
