### ISSUE TITLE
UX redesign - Feature Requested

### ISSUE THREAD

**Issue by Pargat-Dhanjal** [CyBear-Jinni/CBJ_Site#99]
Would gladly work on the entire UI redesign for the web application.

**Comment by guyluz11** [comment]
It is built using flutter

**Comment by Pargat-Dhanjal** [comment]
@guyluz11 well I surely can make new designs for the website then but I won't be able to contribute to the project as I am not a flutter developer 😔

**Comment by guyluz11** [comment]
Ok, so I guess that I will close this issue, thanks hanks anyway for wanting to contribute.
